### ISSUE TITLE
Camera shifting

### ISSUE THREAD

**Issue by PignoulMarcel** [OopsOverflow/MonCraft#7]
Camera slightly shifting after moving the cube ~e-6.
Maybe the difference between 2 mouse value is not set to null after releasing clic.

(tested on IceCube)

![image](https://user-images.githubusercontent.com/49788792/113904179-14a1b380-97d2-11eb-86f2-76e488d38ca3.png)

**Comment by k2d222** [comment]
When does the issue appears and how can we reproduce it ?
The issue might be, that a translation of 0 in camera space (local space) will cause a slight motion due to float math.
`position = glm::inverse(view) * trans * view * glm::vec4(position, 1.f);`
If that is the culprit I don't think it will cause any problems as it is imperceptible.

**Comment by PignoulMarcel** [comment]
This seems to happen when you release the mouse while it is moving

This issue is not rly important but might be a problem for long pause or fast moving -> release mouse
